/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code_coverage_java;

public class App {
    public String getGreeting() {
        return "This is a test greeting";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
